vcd_org         = "Test-ENG001"
vcd_vdc         = "TEST-VDC1"
vcd_site        = "fra"
src_catalog     = "CAT_ANSIBLE"
src_template    = "CentOS-7.7-64Bits"
org_net   	= "ORG_NET_TEST_VDC1_NET2"
